### ISSUE TITLE
Create a frontend project locally

### ISSUE THREAD

**Issue by AlessandroDu** [ishouldtrackthat/notes#19]
We will want to create a front end project. This is going to be a few steps because we need to bootstrap the project and get it in GithHub before we can start creating smaller tasks.

Create a project with vite-ts (we specifically want typescript) - https://vite.dev/guide/
Read docs and watch vids on this, but it'll look something like npm create vite@latest ishouldtrackthat -- --template react-ts . You may need to install Node first to get npm running.

We will specifically want the typescript variation (-ts).

**Get that running locally to get an idea of how it works.**

If you need any kind of project name, can just call it ishouldtrackthat

**Check if it has a .gitignore**, if it doesn't, add a template from online. This will prevent us from spamming the repo with a bunch of generated library files.

**Comment by jialiangwu4** [comment]
Created a frontend project locally using Vite. 

Created a [frontend repo ](https://github.com/ishouldtrackthat/frontend) and pushed code into this repo
