### ISSUE TITLE
Research: Most Popular CICD tools

### ISSUE THREAD

**Issue by CalebCurry** [ishouldtrackthat/notes#2]
Let's automate as much as makes sense. What tools can we use to improve our source code, security, performance, etc. All these should be able to tie in to a CICD pieline.

These may be language specific, such as running `Rust Analyzer Check` or some other tools.

Note that certain things can stop a CICD pipeline, other things can just emit warnings.

Example: unused variables. Not ideal but probably not the end of the world either (unless you are using Go 😆)

**Comment by sammyinfosec** [comment]
Attached is list of Categories of tools to implement in the CICD pipeline. 





[Research-CICD.xlsx](https://github.com/user-attachments/files/17352829/Research-CICD.xlsx)
